version: '3'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - .:/app
        ports:
          - 5000
        environment:
          - PYTHONPATH=/app/src
          - WORKON_HOME=/app/pipenv
          - OPENWEATHER_API_KEY
          - TEST_OPENWEATHER_API_KEY
